name: Main Build

on:
   push:
     branches: [ master ]
   pull_request:
     branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Check out the repo"
        uses: "actions/checkout@v3"
    - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          cache: "yarn"
          node-version: "lts/*"
    - name: Install dependencies
      run: |
        yarn install
    - name: Lint
      run: |
        yarn lint
    - name: Test
      run: |
        yarn test
      env:
        ETHERSCAN_KEY: ${{ secrets.ETHERSCAN_KEY }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        MAINNET_PRIVATE_KEY: ${{ secrets.MAINNET_PRIVATE_KEY }}
        ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}